inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'decouplio.gemspec'
    - vendor/**/*

Style/Documentation:
  Enabled: false

Style/SignalException:
  Enabled: false

Layout/LineLength:
  Max: 120

Lint/NestedMethodDefinition:
  Exclude:
    - spec/**/*

Lint/UnreachableCode:
  Exclude:
    - spec/**/*

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/BlockLength:
  ExcludedMethods: ['describe','context', 'lambda', 'logic']

Metrics/ModuleLength:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - spec/**/*

RSpec/DescribeClass:
  Enabled: false

RSpec/NestedGroups:
  Max: 10

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Enabled: false

Naming/PredicateName:
  Exclude:
    - lib/decouplio/step.rb
