require: rubocop-rspec

AllCops:
  Exclude:
    - 'decouplio.gemspec'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
    Max: 120

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/BlockLength:
  ExcludedMethods: ['describe','context']

RSpec/DescribeClass:
  Enabled: false

RSpec/NestedGroups:
  Max: 4
