inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'decouplio.gemspec'
    - vendor/**/*

Style/Documentation:
  Enabled: false

Style/SignalException:
  Enabled: false

Layout/LineLength:
  Max: 120

Lint/Void:
  Exclude:
    - spec/support/matchers/error_matcher.rb

Lint/UnusedBlockArgument:
  Exclude:
    - spec/support/matchers/error_matcher.rb
    - spec/support/matchers/decouplio_action_matcher.rb

Lint/NestedMethodDefinition:
  Exclude:
    - spec/**/*

Lint/UnreachableCode:
  Exclude:
    - spec/**/*

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/BlockLength:
  IgnoredMethods: ['describe','context', 'lambda', 'logic', 'define']

Metrics/ModuleLength:
  Exclude:
    - lib/decouplio/const/types.rb
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - spec/**/*

RSpec/DescribeClass:
  Enabled: false

RSpec/NestedGroups:
  Max: 10

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Exclude:
    - spec/**/*

Naming/PredicateName:
  Exclude:
    - lib/decouplio/step.rb
