version: 2

executors:
  test_executor:
    docker:
      - image: circleci/ruby:${RUBY_VERSION}
    working_directory: ~/decouplio

jobs:
  build:
    environment:
      RUBY_VERSION: << parameters.ruby_version >>
      BUNDLER_VERSION: 2.1.4
    working_directory: ~/decouplio
    executor: test_executor
    parameters:
      ruby_version:
        type: string
    steps:
      - checkout

      - run:
          name: Install bundler
          command: gem install bundler:2.1.2

      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

      - run:
          name: Run Rubocop
          command: bundle exec rubocop -P

      - run:
          name: Run Tests
          command: bundle exec rspec

workflows:
  build_and_test:
    jobs:
      - build:
          name: 'ruby 2.5.9'
          ruby_version: 2.5.9
      - build:
          name: 'ruby 2.6.8'
          ruby_version: 2.6.8
      - build:
          name: 'ruby 2.7.0'
          ruby_version: 2.7.0
      - build:
          name: 'ruby 3.0.3'
          ruby_version: 3.0.3
