version: 2
jobs:
  build:
    working_directory: ~/decouplio
    docker:
      - image: ruby:2.7.0
    steps:
      - checkout

      - run:
          name: Install bundler
          command: gem install bundler:2.1.2

      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

      - save_cache:
          key: decouplio-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Run Rubocop
          command: bundle exec rubocop -P

      - run:
          name: Run Tests
          command: bundle exec rspec
